version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "$TASK_DEFINITION"
        LoadBalancerInfo:
          ContainerName: "$CONTAINER_NAME"
          ContainerPort: "$CONTAINER_PORT"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["$SUBNET_1","$SUBNET_2","$SUBNET_3"]
            SecurityGroups: ["$SECURITY_GROUP"]
            AssignPublicIp: "DISABLED"
        CapacityProviderStrategy:
          - Weight: "$CAPACITY_PROVIDER_WEIGHT"
            CapacityProvider: "$CAPACITY_PROVIDER"    
